# Generated by Django 5.0.2 on 2024-02-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('roll', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('Admission_date', models.DateField()),
                ('Exam_date', models.DateTimeField()),
                ('Result', models.DecimalField(decimal_places=2, max_digits=3)),
                ('address', models.TextField()),
                ('father_name', models.TextField(default='Rahim')),
                ('PlayCricket', models.BooleanField()),
                ('class_duration', models.DurationField()),
                ('class_start_time', models.TimeField()),
            ],
        ),
    ]
